apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nexus.ravindra.tech/sampleapp:24e5fcac42508d6f6f271423fe40ef0f0c220e1f
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: phoenix-docker
