name: site-security-scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ mail ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
    - name: Envsubst test
      run: |
        pwd
        echo "Before"
        cat manifiest/deployment.yaml

        export tag="latest2"

        envsubst < manifiest/deployment.yaml.tmpl > manifiest/deployment.yaml

        echo "After"

        cat manifiest/deployment.yaml

