name: site-security-scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ mail ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
    - name: Envsubst test
      run: |
        echo "Before"
        cat ${{ github.workspace }}/manifiest/deployment.yaml

        export tag="latest2"

        envsubst < ${{ github.workspace }}/manifiest/deployment.yaml.tmpl > ${{ github.workspace }}/manifiest/deployment.yaml

        echo "After"

        cat ${{ github.workspace }}/manifiest/deployment.yaml

